markdown: rdiscount
permalink: /:title/
url: http://zhongpei.me
name: zhongpei.me
author: zhongpei
qq: 
email: 
duoshuo: yonsm
beian: 
cnzz: 119959
weibo: 
github: 
pygments: true
safe: true
paginate: 20
about: "这里是 zhongpei 的个人博客"
